apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-orchestrator
  namespace: argocd
spec:
  project: studying
  source:
    repoURL: git@github.com:Alves0611/crossplane-argocd.git
    targetRevision: main
    path: argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
