apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: studying-node-group-role
  labels:
    environment: dev
    managed-by: crossplane
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            }
          }
        ]
      }
    tags:
      Name: studying-node-group-role
      Environment: dev
      ManagedBy: crossplane
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: studying-node-group-eks-worker-node-policy
  labels:
    environment: dev
    managed-by: crossplane
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    roleRef:
      name: studying-node-group-role
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: studying-node-group-eks-cni-policy
  labels:
    environment: dev
    managed-by: crossplane
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    roleRef:
      name: studying-node-group-role
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: studying-node-group-ecr-read-only
  labels:
    environment: dev
    managed-by: crossplane
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    roleRef:
      name: studying-node-group-role
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: studying-node-group-ssm-managed-instance
  labels:
    environment: dev
    managed-by: crossplane
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    roleRef:
      name: studying-node-group-role
  providerConfigRef:
    name: default
